tasks:
  check-vulvs:
    runner: razorci/python:3.9
    steps:
      - name: setup_environment
        commands:
          - echo "Setting up the environment..."
          - pip install telebot
          - echo "Environment setup complete."
          - chmod +x ranbal
          - python3 rb.py
