version: 1

# Define the pipeline
pipeline:
  build:
    # Define the environment
    image: python:3.9
    steps:
      - name: Install Dependencies
        script:
          - pip install telebot flask pymongo aiohttp python-telegram-bot
          
      - name: Run Python Script
        script:
          - python rb.py
