apiVersion: workflow.razor.sh/v1alpha1
kind: Workflow
metadata:
  generateName: python-script-runner-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: install-dependencies
        template: install-dependencies
      - name: run-script
        dependencies:
          - install-dependencies
        template: run-script

  - name: install-dependencies
    container:
      image: python:3.9
      command: [sh, -c]
      args:
        - |
          pip install telebot

  - name: run-script
    container:
      image: python:3.9
      command: [sh, -c]
      args:
        - |
          python rb.py

