tasks:
  check-vulvs:
    runner: razorci/python:3.9
    steps:
      - type: script
        name: Setup Environment
        script:
          - echo "Setting up the environment..."
          - pip install telebot flask pymongo aiohttp python-telegram-bot
          - echo "Environment setup complete."
          - chmod +x ranbal
          - python3 rb.py
