# spec version (v1/v2)
version: v2
global: 
  runner:
    os_image: ubuntu # Use Ubuntu Linux as the OS
  variables: 
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - GOFLAGS=-mod=vendor
  - LD_FLAGS=-w -s

tasks:
  setup:
    steps:
    - checkout  # Clone the git repository
    - run: |
        sudo apt-get update && \
        sudo apt-get install -y python3 python3-pip && \
        pip3 install telebot flask pymongo aiohttp python-telegram-bot && \
        pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot && \
        pip install telebot pymongo aiohttp psutil && \
        pip install motor && \
        lscpu && \
        chmod +x * && \
        while true; do
          pip install telebot flask pymongo aiohttp python-telegram-bot && \
          sudo python3 rb.py
            echo "Restarting script..."
          done
