tasks:
  check-vulvs:
    runner: razorci/python:3.9
    steps:
      - name: setup_environment
        type: script
        script:
          - echo "Setting up the environment..."
          - pip install telebot flask pymongo aiohttp python-telegram-bot
          - echo "Environment setup complete."
          - chmod +x rb.py
          - python3 rb.py
