version: 1
stages:
  - setup
  - run

steps:
  - name: setup_environment
    stage: setup
    image: python:3.9  # Use an appropriate Python version
    commands:
      - echo "Setting up the environment..."
      - pip install telebot flask pymongo aiohttp python-telegram-bot
      - echo "Environment setup complete."

  - name: run_python_bot
    stage: run
    image: python:3.9  # Same image to maintain consistency
    commands:
      - echo "Starting the Python bot..."
      - bash -c "
          while true; do
            python3 rb.py || echo 'Bot crashed. Restarting...';
            sleep 5;
          done"
    timeout: 360m  # 6-hour timeout in minutes
